name: migrator

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-migrator-docker-${{ github.sha }}
          restore-keys: ${{ runner.os }}-migrator-docker-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate tags
        id: generate-tags
        uses: hulloitskai/generate-docker-tags-action@v0.2.1
        with:
          repo: hulloitskai/home-migrator
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./migrator/
          push: true
          tags: ${{ steps.generate-tags.outputs.tags }}
          cache-from: |
            type=local,src=/tmp/.docker-cache
          cache-to: |
            type=local,dest=/tmp/.docker-cache,mode=max
